import { z } from "zod";

export const configSchema = z.object({
  NEXT_PUBLIC_API_URL_SERVER: z.string(),
  NEXT_PUBLIC_API_URL_SERVER_TUNNEL: z.string(),
  NEXT_PUBLIC_API_URL_SERVER_BASE: z.string(),
  NEXT_PUBLIC_API_URL_CLIENT: z.string(),
  NEXT_PUBLIC_TOKEN_TEST: z.string(),
  NEXT_PUBLIC_CLOUD_API: z.string(),
  NEXT_PUBLIC_PAGE_SIZE: z.string(),
  NEXT_PUBLIC_ROOT_PARENT_INDUSTRY_ID: z.string(),
  NEXT_PUBLIC_JWT_SECRET: z.string(),

  NEXT_PUBLIC_ROLE_SUPER_ADMIN: z.string(),
  NEXT_PUBLIC_ROLE_RECRUITER: z.string(),
  NEXT_PUBLIC_ROLE_RECRUITER_ADMIN: z.string(),
  NEXT_PUBLIC_ROLE_CANDIDATE: z.string(),
  NEXT_PUBLIC_ROLE_GUEST: z.string(),
  NEXT_PUBLIC_ROLE_CONTENT_MANAGER: z.string(),
});

const configProject = configSchema.safeParse({
  NEXT_PUBLIC_API_URL_SERVER: process.env.NEXT_PUBLIC_API_URL_SERVER,
  NEXT_PUBLIC_API_URL_SERVER_TUNNEL: process.env.NEXT_PUBLIC_API_URL_SERVER_TUNNEL,
  NEXT_PUBLIC_API_URL_SERVER_BASE: process.env.NEXT_PUBLIC_API_URL_SERVER_BASE,
  NEXT_PUBLIC_API_URL_CLIENT: process.env.NEXT_PUBLIC_API_URL_CLIENT,
  NEXT_PUBLIC_TOKEN_TEST: process.env.NEXT_PUBLIC_TOKEN_TEST,
  NEXT_PUBLIC_CLOUD_API: process.env.NEXT_PUBLIC_CLOUD_API,
  NEXT_PUBLIC_PAGE_SIZE: process.env.NEXT_PUBLIC_PAGE_SIZE,
  NEXT_PUBLIC_ROOT_PARENT_INDUSTRY_ID:
    process.env.NEXT_PUBLIC_ROOT_PARENT_INDUSTRY_ID,
  NEXT_PUBLIC_JWT_SECRET: process.env.NEXT_PUBLIC_JWT_SECRET,

  NEXT_PUBLIC_ROLE_SUPER_ADMIN: process.env.NEXT_PUBLIC_ROLE_SUPER_ADMIN,
  NEXT_PUBLIC_ROLE_RECRUITER: process.env.NEXT_PUBLIC_ROLE_RECRUITER,
  NEXT_PUBLIC_ROLE_RECRUITER_ADMIN:
    process.env.NEXT_PUBLIC_ROLE_RECRUITER_ADMIN,
  NEXT_PUBLIC_ROLE_CANDIDATE: process.env.NEXT_PUBLIC_ROLE_CANDIDATE,
  NEXT_PUBLIC_ROLE_GUEST: process.env.NEXT_PUBLIC_ROLE_GUEST,
  NEXT_PUBLIC_ROLE_CONTENT_MANAGER:
    process.env.NEXT_PUBLIC_ROLE_CONTENT_MANAGER,
});

if (!configProject.success) {
  console.error(configProject.error.issues);
  throw new Error("Các giá trị khai báo trong file .env không hợp lệ");
}
export const envConfig = configProject.data;
