services:
  backend:
    container_name: do_an_khoa-server
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./server/.env.prod
    environment:
      PORT: "${BACKEND_PORT}"
      FRONTEND_URL: "http://${SERVER_IP}:${FRONTEND_PORT}"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - redis
    networks:
      - jobhub-network

  frontend:
    container_name: do_an_khoa-client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "http://${SERVER_IP}:${BACKEND_PORT}"
        NEXT_PUBLIC_API_URL_SERVER: "http://${SERVER_IP}:${BACKEND_PORT}/api"
        NEXT_PUBLIC_API_URL_SERVER_BASE: "http://${SERVER_IP}:${BACKEND_PORT}"
        NEXT_PUBLIC_API_URL_CLIENT: "http://${SERVER_IP}:${FRONTEND_PORT}"
        NEXT_PUBLIC_SEPAY_BASE_URL: "${NEXT_PUBLIC_SEPAY_BASE_URL}"
        NEXT_PUBLIC_SEPAY_ACCOUNT: "${NEXT_PUBLIC_SEPAY_ACCOUNT}"
        NEXT_PUBLIC_SEPAY_BANK: "${NEXT_PUBLIC_SEPAY_BANK}"
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: "http://${SERVER_IP}:${BACKEND_PORT}"
      NEXT_PUBLIC_API_URL_SERVER: "http://${SERVER_IP}:${BACKEND_PORT}/api"
      NEXT_PUBLIC_API_URL_SERVER_BASE: "http://${SERVER_IP}:${BACKEND_PORT}"
      NEXT_PUBLIC_API_URL_CLIENT: "http://${SERVER_IP}:${FRONTEND_PORT}"
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    networks:
      - jobhub-network

  redis:
    image: redis:alpine
    container_name: do_an_khoa-redis
    restart: unless-stopped
    networks:
      - jobhub-network

networks:
  jobhub-network:
    driver: bridge
