server {
    listen 80;

    # Cấu hình cho Frontend
    location / {
        proxy_pass http://do_an_khoa-client:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Cấu hình cho Backend (API)
    location /api {
        proxy_pass http://do_an_khoa-server:2302;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Hỗ trợ truyền Cookie và thông tin đăng nhập
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header Set-Cookie;
    }
}
