import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import TanstackProvider from "@/components/TanstackProvider";
import { Toaster } from "@/components/ui/sonner";
import { ColorThemeProvider } from "@/components/ColorThemeProvider";
import BackToTop from "@/components/BackToTop";
import BlockWrap from "./BlockWrap";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Jobs",
  description: "Generated by create next app",
  icons: {
    icon: "job.svg",
  },
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                const theme = localStorage.getItem('theme') || 'system';
                const colorTheme = localStorage.getItem('color-theme') || 'Default';
                const root = document.documentElement;
                
                if (theme === 'dark' || 
                    (theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  root.classList.add('dark');
                } else {
                  root.classList.remove('dark');
                }

                root.setAttribute('data-color-theme', colorTheme);
              } catch (e) {}
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased px-5`}
      >
        <TanstackProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ColorThemeProvider>
              <BackToTop />
              <BlockWrap>
                <NextIntlClientProvider messages={messages}>
                  {children}
                </NextIntlClientProvider>
              </BlockWrap>
              <Toaster position="top-right" richColors />
            </ColorThemeProvider>
          </ThemeProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
